# Generated by Django 4.2.16 on 2026-01-26 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, choices=[('< 1.000 €', 'Under €1.000'), ('1.000 – 2.000 €', '€1.000 – €2.000'), ('2.000 – 4.000 €', '€2.000 – €4.000'), ('4.000 €+', '€4.000+'), ('Not sure', 'Not sure yet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='project_type',
            field=models.CharField(choices=[('Essential Website', 'Essential Website'), ('Business Website', 'Business Website'), ('Custom Web Application', 'Custom Web Application'), ('Not sure yet', 'Not sure yet / Let’s discuss')], default='Not specified', max_length=50),
            preserve_default=False,
        ),
    ]
